### ISSUE TITLE
'NA' values incompatible with depth filter, str instead of int

### ISSUE THREAD

**Issue by jasonwalker80** [genome/docker-depth-filter#1]
Example error:
```
Traceback (most recent call last):
  File "/usr/bin/depth_filter.py", line 105, in <module>
    main()
  File "/usr/bin/depth_filter.py", line 93, in main
    if(depth < args.minimum_depth):
TypeError: '<' not supported between instances of 'str' and 'int'
```

https://github.com/genome/docker-depth-filter/blob/4bd2d12607382113a8f6bb0870b4347d8f2a2008/depth_filter.py#L83

**Comment by jasonwalker80** [comment]
It looks like v0.1.1 will fix this. The commit was on the master branch, but had not made it to a versioned release.
